import { Router } from 'express'; import argon2 from 'argon2'; import jwt from 'jsonwebtoken'; import crypto from 'crypto'; import { z } from 'zod';
import { query } from '../db.js'; import { AppError } from '../errors.js'; import { accessToken, refreshToken, setRefreshCookie, clearRefreshCookie, requireAuth } from '../auth.js'; import { config } from '../config.js'; import { sendPasswordResetEmail } from '../mailer.js';
const router=Router();
// Regex de email (formato estandar) + contrasena con minimo 8, una letra y un numero.
const emailRegex=/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;
const emailSchema=z.string().trim().max(254).regex(emailRegex,'Correo electrónico inválido');
const passwordSchema=z.string().min(8,'La contraseña debe tener al menos 8 caracteres').max(128).regex(/[A-Za-zÁÉÍÓÚáéíóúÑñ]/,'La contraseña debe incluir al menos una letra').regex(/[0-9]/,'La contraseña debe incluir al menos un número');
const nameSchema=z.string().trim().min(2,'El nombre debe tener al menos 2 caracteres').max(80).regex(/[\p{L}\p{N}]/u,'El nombre no puede tener solo espacios');
const credentials=z.object({email:emailSchema,password:passwordSchema,name:nameSchema.optional()});
// Login valida formato y longitud máxima solamente. Reglas de contraseña nueva
// (letra/número/mínimo) no deben impedir verificar cuentas existentes.
const loginCredentials=z.object({email:emailSchema,password:z.string().min(1,'Escribe tu contraseña.').max(128)});
const authResponse=(res,user)=>{setRefreshCookie(res,refreshToken(user)); res.json({accessToken:accessToken(user),user:{id:user.id,email:user.email,name:user.name,role:user.role}});};
router.post('/register',async(req,res,next)=>{try{const parsed=credentials.extend({name:z.string().trim().min(2).max(80)}).parse(req.body); const data={...parsed,email:parsed.email.trim().toLowerCase()}; const exists=await query('SELECT 1 FROM users WHERE email=$1',[data.email]); if(exists.rowCount) throw new AppError(409,'No fue posible crear la cuenta'); const hash=await argon2.hash(data.password,{type:argon2.argon2id,memoryCost:19456,timeCost:2,parallelism:1}); const r=await query('INSERT INTO users(email,password_hash,name) VALUES($1,$2,$3) RETURNING id,email,name,role',[data.email,hash,data.name]); authResponse(res,r.rows[0]);}catch(e){next(e);}});
router.post('/login',async(req,res,next)=>{try{const parsed=loginCredentials.parse(req.body); const data={...parsed,email:parsed.email.trim().toLowerCase()}; const r=await query('SELECT id,email,name,role,password_hash FROM users WHERE email=$1',[data.email]); const user=r.rows[0]; if(!user) throw new AppError(401,'No existe una cuenta con ese correo.'); let verified=false; try { verified=await argon2.verify(user.password_hash,data.password); } catch (error) { console.error('No se pudo verificar password_hash para usuario',user.id,error); throw new AppError(500,'No se pudo verificar la contraseña de esta cuenta.'); } if(!verified) throw new AppError(401,'La contraseña es incorrecta.'); authResponse(res,user);}catch(e){next(e);}});
router.post('/refresh',async(req,res,next)=>{try{const token=req.cookies.smartdj_refresh; if(!token) throw new AppError(401,'Sesión expirada'); const p=jwt.verify(token,config.refreshSecret); const r=await query('SELECT id,email,name,role FROM users WHERE id=$1',[p.sub]); if(!r.rowCount) throw new AppError(401,'Sesión expirada'); authResponse(res,r.rows[0]);}catch(e){next(new AppError(401,'Sesión expirada'));}});
router.post('/logout',(_req,res)=>{clearRefreshCookie(res);res.status(204).end();});
// Solicitud de recuperacion: responde siempre 200 (no revela si el correo existe).
router.post('/forgot-password',async(req,res,next)=>{try{const {email}=z.object({email:emailSchema}).parse(req.body);const generic={message:'Si el correo existe, te enviamos un enlace para restablecer tu contraseña.'};const r=await query('SELECT id,email FROM users WHERE email=$1',[email.toLowerCase()]);if(!r.rowCount)return res.json(generic);const user=r.rows[0];const token=crypto.randomBytes(32).toString('hex');const tokenHash=crypto.createHash('sha256').update(token).digest('hex');await query('INSERT INTO password_resets(user_id,token_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL \'30 minutes\')',[user.id,tokenHash]);const sent=await sendPasswordResetEmail(user.email,token);res.json(sent.demo?{...generic,resetToken:token}:generic);}catch(e){next(e);}});
// Cambio de contrasena usando el token recibido por correo.
router.post('/reset-password',async(req,res,next)=>{try{const {token,password}=z.object({token:z.string().trim().min(10),password:passwordSchema}).parse(req.body);const tokenHash=crypto.createHash('sha256').update(token).digest('hex');const r=await query('SELECT id,user_id FROM password_resets WHERE token_hash=$1 AND used_at IS NULL AND expires_at>NOW()',[tokenHash]);if(!r.rowCount)throw new AppError(400,'El enlace es inválido o ya expiró');const reset=r.rows[0];const hash=await argon2.hash(password,{type:argon2.argon2id,memoryCost:19456,timeCost:2,parallelism:1});await query('UPDATE users SET password_hash=$1 WHERE id=$2',[hash,reset.user_id]);await query('UPDATE password_resets SET used_at=NOW() WHERE id=$1',[reset.id]);res.json({message:'Contraseña actualizada correctamente'});}catch(e){next(e);}});
router.get('/me',requireAuth,async(req,res,next)=>{try{const r=await query('SELECT id,email,name,role FROM users WHERE id=$1',[req.user.sub]); if(!r.rowCount) throw new AppError(404,'Usuario no encontrado'); res.json(r.rows[0]);}catch(e){next(e);}});
export default router;
