import { Router } from 'express'; import { z } from 'zod'; import axios from 'axios'; import { query } from '../db.js'; import { requireAuth } from '../auth.js'; import { AppError } from '../errors.js'; import { config } from '../config.js';
const router=Router(); router.use(requireAuth);
const venueSchema=z.object({name:z.string().trim().min(2).max(120),kind:z.enum(['restaurant','cafe','salsa_bar','nightclub','lounge','other']),ambience:z.string().trim().min(2).max(500)});
router.get('/',async(req,res,next)=>{try{const r=await query('SELECT * FROM establishments WHERE owner_id=$1 ORDER BY created_at DESC',[req.user.sub]);res.json(r.rows);}catch(e){next(e);}});
router.post('/',async(req,res,next)=>{try{const d=venueSchema.parse(req.body);const r=await query('INSERT INTO establishments(owner_id,name,kind,ambience,public_code) VALUES($1,$2,$3,$4,encode(gen_random_bytes(6),\'hex\')) RETURNING *',[req.user.sub,d.name,d.kind,d.ambience]);res.status(201).json(r.rows[0]);}catch(e){next(e);}});
router.get('/:id/dashboard',async(req,res,next)=>{try{const venue=await query('SELECT * FROM establishments WHERE id=$1 AND owner_id=$2',[req.params.id,req.user.sub]);if(!venue.rowCount)throw new AppError(404,'Establecimiento no encontrado');const requests=await query('SELECT * FROM song_requests WHERE establishment_id=$1 ORDER BY created_at DESC LIMIT 30',[venue.rows[0].id]);res.json({venue:venue.rows[0],requests:requests.rows});}catch(e){next(e);}});
router.get('/:id/search',async(req,res,next)=>{try{const ownership=await query('SELECT 1 FROM establishments WHERE id=$1 AND owner_id=$2',[req.params.id,req.user.sub]);if(!ownership.rowCount)throw new AppError(404,'Establecimiento no encontrado');const term=z.string().min(2).max(100).parse(req.query.q); const {data}=await axios.get('https://itunes.apple.com/search',{params:{term,media:'music',limit:15},timeout:5000});res.json(data.results.map(x=>({title:x.trackName,artist:x.artistName,genre:x.primaryGenreName,previewUrl:x.previewUrl,artwork:x.artworkUrl100,bpm:null})));}catch(e){next(e);}});
router.post('/:id/analyze',async(req,res,next)=>{try{const ownership=await query('SELECT 1 FROM establishments WHERE id=$1 AND owner_id=$2',[req.params.id,req.user.sub]);if(!ownership.rowCount)throw new AppError(404,'Establecimiento no encontrado');const d=z.object({currentGenre:z.string(),requestedGenre:z.string(),currentBpm:z.number().positive(),requestedBpm:z.number().positive(),currentKey:z.string(),requestedKey:z.string()}).parse(req.body);const a=await axios.post(`${config.aiUrl}/compatibility`,d);res.json(a.data);}catch(e){next(e);}});
export default router;
